### ISSUE TITLE
MarchHare::ChannelAlreadyClosed after Acknowledge

### ISSUE THREAD

**Issue by brianbroderick** [mxenabled/action_subscriber#66]
Everything works fine for a variable amount of time (15-60 minutes on average), but eventually I get this error:

```
Error processing message: MarchHare::ChannelAlreadyClosed
Backtrace: /app/vendor/bundle/jruby/2.2.0/gems/march_hare-2.16.0-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'
/app/vendor/bundle/jruby/2.2.0/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:976:in `converting_rjc_exceptions_to_ruby'
/app/vendor/bundle/jruby/2.2.0/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:748:in `basic_ack'
/app/vendor/bundle/jruby/2.2.0/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:663:in `block in ack'
org/jruby/RubyProc.java:318:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:991:in `guarding_against_stale_delivery_tags'
/app/vendor/bundle/jruby/2.2.0/gems/march_hare-2.16.0-java/lib/march_hare/channel.rb:662:in `ack'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/middleware/env.rb:45:in `acknowledge'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/base.rb:60:in `acknowledge'
/app/app/subscribers/semantria_activity_subscriber.rb:13:in `created'
org/jruby/RubyKernel.java:1823:in `public_send'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/dsl.rb:81:in `block in run_action_with_filters'
org/jruby/RubyProc.java:318:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/dsl.rb:86:in `run_action_with_filters'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/middleware/router.rb:12:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/middleware/active_record/query_cache.rb:14:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/middleware/active_record/connection_management.rb:10:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/middleware/decoder.rb:15:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/middleware/error_handler.rb:11:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/march_hare/subscriber.rb:76:in `block in enqueue_env'
/app/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/app/vendor/bundle/jruby/2.2.0/gems/action_subscriber-2.4.0-java/lib/action_subscriber/march_hare/subscriber.rb:75:in `block in enqueue_env'
org/jruby/RubyProc.java:318:in `call'
/app/vendor/bundle/jruby/2.2.0/gems/lifeguard-0.0.9/lib/lifeguard/threadpool.rb:75:in `block in async'
```

I'm running JRuby 9.0.5.0 and action_subscriber (2.4.0-java)

Since it's dying on acknowledge, the message is never cleared and the thread is essentially "stuck".  Once this happens on all 5 of my threads, the service essentially stops.

**Comment by brianbroderick** [comment]
Here is my subscriber:

```
def created
  ::Load::PostAnalysis.call(payload)
rescue => exception
  ::ErrorLog.notify(exception)
ensure
  acknowledge
end
```

**Comment by mmmries** [comment]
@brianbroderick you might want to do test this again after doing a `bundle update lifeguard`. We found some issues with how `lifeguard` was managing the threadpool that were causing our subscribers to freeze. It didn't require an update to this gem, but it has helped our stability quite a bit.

**Comment by brianbroderick** [comment]
@mmmries Thanks.  I updated lifeguard and am seeing a different issue.  I'll post it on that project.

**Comment by abrandoned** [comment]
fixed in action_subscriber 4+
